// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum SearchRequest_Corpus

typedef GPB_ENUM(SearchRequest_Corpus) {
  SearchRequest_Corpus_Universal = 0,
  SearchRequest_Corpus_Web = 1,
  SearchRequest_Corpus_Images = 2,
  SearchRequest_Corpus_Local = 3,
  SearchRequest_Corpus_News = 4,
  SearchRequest_Corpus_Products = 5,
  SearchRequest_Corpus_Video = 6,
};

GPBEnumDescriptor *SearchRequest_Corpus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL SearchRequest_Corpus_IsValidValue(int32_t value);

#pragma mark - SearchRequestRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SearchRequestRoot : GPBRootObject
@end

#pragma mark - SearchRequest

typedef GPB_ENUM(SearchRequest_FieldNumber) {
  SearchRequest_FieldNumber_Query = 1,
  SearchRequest_FieldNumber_PageNumber = 2,
  SearchRequest_FieldNumber_ResultPerPage = 3,
  SearchRequest_FieldNumber_Corpus = 4,
};

@interface SearchRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *query;
/** Test to see if @c query has been set. */
@property(nonatomic, readwrite) BOOL hasQuery;

@property(nonatomic, readwrite) int32_t pageNumber;

@property(nonatomic, readwrite) BOOL hasPageNumber;
@property(nonatomic, readwrite) int32_t resultPerPage;

@property(nonatomic, readwrite) BOOL hasResultPerPage;
@property(nonatomic, readwrite) SearchRequest_Corpus corpus;

@property(nonatomic, readwrite) BOOL hasCorpus;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
