// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class SearchResponse_Result;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SearchResponseRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SearchResponseRoot : GPBRootObject
@end

#pragma mark - SearchResponse

typedef GPB_ENUM(SearchResponse_FieldNumber) {
  SearchResponse_FieldNumber_ResultArray = 1,
};

@interface SearchResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SearchResponse_Result*> *resultArray;
/** The number of items in @c resultArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resultArray_Count;

@end

#pragma mark - SearchResponse_Result

typedef GPB_ENUM(SearchResponse_Result_FieldNumber) {
  SearchResponse_Result_FieldNumber_URL = 1,
  SearchResponse_Result_FieldNumber_Title = 2,
  SearchResponse_Result_FieldNumber_SnippetsArray = 3,
};

@interface SearchResponse_Result : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;
/** Test to see if @c URL has been set. */
@property(nonatomic, readwrite) BOOL hasURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;
/** Test to see if @c title has been set. */
@property(nonatomic, readwrite) BOOL hasTitle;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *snippetsArray;
/** The number of items in @c snippetsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger snippetsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
